import discord
from discord.ext import commands
import io
from datetime import timezone


def _avatar_url(user: discord.abc.User) -> str:
    if user.avatar:
        return str(user.avatar.url)
    return f"https://cdn.discordapp.com/embed/avatars/{int(user.discriminator or 0) % 5}.png"


def _role_colour(member) -> str:
    if isinstance(member, discord.Member) and member.color != discord.Color.default():
        return f"#{member.color.value:06x}"
    return "#dcddde"


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
    )


def _render_embed(embed: discord.Embed) -> str:
    try:
        colour = f"#{embed.colour.value:06x}" if embed.colour and embed.colour.value else "#5865f2"
    except Exception:
        colour = "#5865f2"

    parts = [f'<div class="embed" style="border-left:4px solid {colour}">']

    if embed.author and embed.author.name:
        parts.append(f'<div class="embed-author">{_escape(embed.author.name)}</div>')
    if embed.title:
        parts.append(f'<div class="embed-title">{_escape(embed.title)}</div>')
    if embed.description:
        desc = _escape(embed.description).replace("\n", "<br>")
        parts.append(f'<div class="embed-desc">{desc}</div>')
    for field in embed.fields:
        parts.append(
            f'<div class="embed-field">'
            f'<div class="embed-field-name">{_escape(field.name)}</div>'
            f'<div class="embed-field-value">{_escape(field.value).replace(chr(10), "<br>")}</div>'
            f'</div>'
        )
    if embed.image and embed.image.url:
        parts.append(f'<div class="embed-image"><img src="{_escape(embed.image.url)}" alt="embed image"></div>')
    if embed.footer and embed.footer.text:
        parts.append(f'<div class="embed-footer">{_escape(embed.footer.text)}</div>')

    parts.append("</div>")
    return "\n".join(parts)


HTML_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #313338;
    color: #dcddde;
    font-family: 'Whitney', 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 15px;
    line-height: 1.4;
    padding: 20px;
  }}
  .header {{
    background: #1e1f22;
    border-radius: 8px;
    padding: 16px 20px;
    margin-bottom: 24px;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }}
  .header h1 {{ font-size: 18px; color: #fff; font-weight: 700; }}
  .header p {{ font-size: 13px; color: #b5bac1; }}
  .messages {{ display: flex; flex-direction: column; gap: 2px; }}
  .msg {{
    display: flex;
    gap: 16px;
    padding: 4px 16px;
    border-radius: 4px;
  }}
  .msg:hover {{ background: #2e3035; }}
  .msg.with-avatar {{ margin-top: 16px; }}
  .avatar {{
    width: 40px;
    height: 40px;
    border-radius: 50%;
    flex-shrink: 0;
    overflow: hidden;
    background: #5865f2;
  }}
  .avatar img {{ width: 100%; height: 100%; object-fit: cover; }}
  .avatar-spacer {{ width: 40px; flex-shrink: 0; }}
  .msg-body {{ flex: 1; min-width: 0; }}
  .msg-header {{ display: flex; align-items: baseline; gap: 8px; margin-bottom: 2px; }}
  .username {{ font-weight: 600; font-size: 15px; }}
  .timestamp {{ font-size: 11px; color: #72767d; }}
  .content {{ color: #dcddde; word-break: break-word; white-space: pre-wrap; }}
  .attachment {{
    margin-top: 6px;
    background: #2b2d31;
    border-radius: 4px;
    padding: 8px 12px;
    font-size: 13px;
    color: #00b0f4;
  }}
  .embed {{
    margin-top: 6px;
    background: #2b2d31;
    border-radius: 4px;
    padding: 12px 16px;
    max-width: 520px;
  }}
  .embed-author {{ font-size: 13px; font-weight: 600; margin-bottom: 4px; }}
  .embed-title {{ font-size: 16px; font-weight: 700; color: #fff; margin-bottom: 6px; }}
  .embed-desc {{ font-size: 14px; color: #dcddde; margin-bottom: 8px; }}
  .embed-field {{ margin-top: 6px; }}
  .embed-field-name {{ font-size: 13px; font-weight: 700; color: #fff; }}
  .embed-field-value {{ font-size: 13px; color: #dcddde; }}
  .embed-image {{ margin-top: 8px; }}
  .embed-image img {{ max-width: 400px; border-radius: 4px; }}
  .embed-footer {{ font-size: 12px; color: #72767d; margin-top: 10px; border-top: 1px solid #3f4147; padding-top: 6px; }}
  .footer {{
    margin-top: 32px;
    text-align: center;
    font-size: 12px;
    color: #72767d;
    padding: 12px;
  }}
</style>
</head>
<body>
"""

HTML_FOOT = """
<div class="footer">Generated by G2G MARKETPLACE Bot &bull; {count} messages</div>
</body>
</html>
"""


async def save_transcript(channel: discord.TextChannel, guild: discord.Guild) -> str:
    """Returns plain-text transcript (stored in DB)."""
    lines = []
    try:
        async for message in channel.history(limit=500, oldest_first=True):
            ts = message.created_at.strftime("%Y-%m-%d %H:%M:%S UTC")
            author = f"{message.author} ({message.author.id})"
            content = message.content or ""
            embeds = [f"[Embed: {e.title or 'untitled'}]" for e in message.embeds]
            attachments = [f"[Attachment: {a.filename}]" for a in message.attachments]
            parts = [content] + embeds + attachments
            lines.append(f"[{ts}] {author}: {' '.join(p for p in parts if p)}")
    except Exception as e:
        lines.append(f"[Error reading transcript: {e}]")
    return "\n".join(lines)


async def build_html_transcript(
    channel: discord.TextChannel,
    guild: discord.Guild,
    ticket: dict,
    closer: discord.Member,
) -> bytes:
    """Returns HTML transcript as bytes for file upload."""
    messages = []
    try:
        async for msg in channel.history(limit=500, oldest_first=True):
            messages.append(msg)
    except Exception:
        pass

    opener_id = ticket.get("opener_id", "?")
    opener = guild.get_member(int(opener_id)) if opener_id != "?" else None
    claimed_id = ticket.get("claimed_by")
    claimer = guild.get_member(int(claimed_id)) if claimed_id else None
    ticket_type = ticket.get("ticket_type", "trade").title()
    opened_at = ticket.get("created_at", "")[:16].replace("T", " ") if ticket.get("created_at") else ""

    header_lines = [
        f"<b>#{_escape(channel.name)}</b> &nbsp;|&nbsp; {_escape(guild.name)}",
        f"Type: <b>{_escape(ticket_type)}</b> &nbsp;|&nbsp; "
        f"Opened by: <b>{_escape(str(opener)) if opener else opener_id}</b>"
        + (f" &nbsp;|&nbsp; Opened at: <b>{opened_at} UTC</b>" if opened_at else ""),
        f"Closed by: <b>{_escape(str(closer))}</b>"
        + (f" &nbsp;|&nbsp; Claimed by: <b>{_escape(str(claimer))}</b>" if claimer else ""),
        f"Messages captured: <b>{len(messages)}</b>",
    ]

    html = HTML_HEAD.format(title=f"Transcript — #{channel.name}")
    html += '<div class="header">\n'
    html += f'<h1>📄 Transcript — #{_escape(channel.name)}</h1>\n'
    for line in header_lines:
        html += f"<p>{line}</p>\n"
    html += "</div>\n"
    html += '<div class="messages">\n'

    prev_author_id = None

    for msg in messages:
        same_author = (prev_author_id == msg.author.id)
        prev_author_id = msg.author.id

        ts = msg.created_at.astimezone(timezone.utc).strftime("%d/%m/%Y %H:%M")
        colour = _role_colour(msg.author)

        if same_author:
            html += '<div class="msg">\n'
            html += '  <div class="avatar-spacer"></div>\n'
        else:
            html += '<div class="msg with-avatar">\n'
            html += f'  <div class="avatar"><img src="{_escape(_avatar_url(msg.author))}" alt="avatar"></div>\n'

        html += '  <div class="msg-body">\n'

        if not same_author:
            html += (
                f'    <div class="msg-header">'
                f'<span class="username" style="color:{colour}">{_escape(str(msg.author.display_name if isinstance(msg.author, discord.Member) else msg.author.name))}</span>'
                f'<span class="timestamp">{_escape(ts)}</span>'
                f'</div>\n'
            )

        if msg.content:
            html += f'    <div class="content">{_escape(msg.content)}</div>\n'

        for embed in msg.embeds:
            html += f"    {_render_embed(embed)}\n"

        for att in msg.attachments:
            html += f'    <div class="attachment">📎 {_escape(att.filename)}</div>\n'

        html += "  </div>\n</div>\n"

    html += "</div>\n"
    html += HTML_FOOT.format(count=len(messages))

    return html.encode("utf-8")


class Transcripts(commands.Cog):
    def __init__(self, bot):
        self.bot = bot


async def setup(bot):
    await bot.add_cog(Transcripts(bot))
